version: "3"

services:
    db:
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      volumes:
      - ./postgres_db/pg_init.sh:/docker-entrypoint-initdb.d/pg_init.sh
      ports:
      - "5432:5432"
      expose:
      - "5432"
    
    web:
        build: frontend
        ports:
          - 3000:3000
        depends_on:
          - api
        stdin_open: true
        tty: true
        # volumes:
        #   - ./frontend:app
        #   - ./app/node_modules

    api:
        build: backend
        environment:
          - DB_HOST=db
        ports:
          - 8000:8000
        depends_on:
          - db
          

